// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrybzkkaphnrturxorff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyeWJ6a2thcGhucnR1cnhvcmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODU1MjEsImV4cCI6MjA2MTI2MTUyMX0.Nks5H6_kFoqf68RmakOgRgWJdU2B4mf7lHa6f4iBDe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);